---
title: "sampleSheet_preprocessing"
author: "Melanie Smith"
date: "2025-08-20"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE,
    cache = FALSE,
    fig.align = "center"
)
```

This RScript is to mutate the existing sample sheet saved with the raw data into a format that minfi can use.  

# Load Libraries

```{r include=FALSE}

# Data manipulation
library(dplyr)
library(readr)
library(stringr)

```

# Set Directories and files

```{r include=FALSE} 
# Set project directory
projectDir <- "D:/VM_Projects/20250820_DNAme_PE" # needs the "windows style" directory path (D:)

# Set input files
metaDataDir <- file.path(projectDir, "metaData")

old_samplesheet_file <- file.path(metaDataDir, "Adelaide_EPIC_sample_sheet.csv")

# Set output files

new_samplesheet_file <- file.path(metaDataDir, "minfi_samplesheet.csv")

```

# Import old samplesheet file

```{r}

# Read your old sheet
old <- read_csv(old_samplesheet_file)

```

# Convert to minfi format and save

```{r}
# Convert to minfi format
minfi_sheet <- old %>%
  # Convert the column names for minfi
  dplyr::mutate(
    Sample_Name = `Sample ID`,
    Sentrix_ID = `Chip No`,
    Sentrix_Position = stringr::str_replace(Position, "R(\\d)C(\\d)", "R0\\1C0\\2")
  ) %>%
  # re-order the columns
  dplyr::select(Sample_Name, Sentrix_ID, Sentrix_Position) %>%
  # add the "Basename" column required by minfi
  dplyr::mutate(
    Basename = paste(Sentrix_ID, Sentrix_Position,sep = "_")
    ) %>%
  # add some information regarding the study (PAC, PE, plasma)
  dplyr::mutate(
    study = case_when(
      str_starts(Sample_Name, "PAC") & str_ends(Sample_Name, "T") ~ "PAC_placenta",
      str_starts(Sample_Name, "S") & str_ends(Sample_Name, "T") ~ "PE_placenta",
      str_starts(Sample_Name, "PAC") & str_ends(Sample_Name, "P") ~ "PAC_plasma",
      str_starts(Sample_Name, "S") & str_ends(Sample_Name, "P") ~ "PE_plasma",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::mutate(
    compartment = case_when(
      endsWith(Sample_Name, "P") ~ "plasma",
      endsWith(Sample_Name, "T") ~ "placenta",
      TRUE ~ NA_character_
    )
  )


# Save as CSV
write_csv(minfi_sheet, new_samplesheet_file)
```

